[package]
name = "math-plotter"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version = "0.12.1", features = ["canvas", "debug"]}

[profile.release]
lto = true
opt-level = 3
panic = "abort"