name: STP Build

on:
  push:
    branches:
      - stp-releases
    tags:
      - stp-v*

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: ${{ matrix.config.target }}
          override: true

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y gcc-multilib
        
      - name: Build
        run: cargo build --release --target ${{ matrix.config.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ github.ref_name }}-${{ matrix.config.os }}
          path: target/${{ matrix.config.target }}/release/